#!/bin/bash

UPDATE_SUBMODULES=conf/update_submodules.sh
[ -f ${UPDATE_SUBMODULES} ] && . ${UPDATE_SUBMODULES} || exit 1

if [ -d conf/kconfig ]; then
 pushd conf/kconfig
 ./bootstrap
 popd
fi

aclocal -I ./conf/m4 --install 

autoheader

libtoolize -c

automake --add-missing --copy

autoconf

echo "#"
echo "# All done... now try to configure using \"./configure --enable-kconfig\""
echo "#"
