#!/bin/bash

# needed to force autoconf looking into subdirectories
touch configure.ac

UPDATE_SUBMODULES=conf/update_submodules.sh
[ -f ${UPDATE_SUBMODULES} ] && . ${UPDATE_SUBMODULES} || exit 1

if [ -d conf/kconfig ]; then
 pushd conf/kconfig
 ./bootstrap
 popd
fi

aclocal -I ./conf/m4 --install 

autoheader

# libtoolize

automake --add-missing --copy -W none

autoconf

echo "#"
echo "# All done... now try to configure using \"./configure --enable-kconfig\""
echo "#"


# To remove a submodule you need to:
# 
# Delete the relevant section from the .gitmodules file.
# Stage the .gitmodules changes git add .gitmodules
# Delete the relevant section from .git/config.
# Run git rm --cached path_to_submodule (no trailing slash).
# Run rm -rf .git/modules/path_to_submodule (no trailing slash).
# Commit git commit -m "Removed submodule "
# Delete the now untracked submodule files rm -rf path_to_submodule